modLoader="javafml" 
license="GNU LESSER GENERAL PUBLIC LICENSE" 
loaderVersion="[36,)" 
issueTrackerURL="https://github.com/HungTeen/pvzmod/issues"

[[mods]]
modId="pvz"
version="0.8.4_PMC"
displayName="Plants vs Zombies"
authors="_HungTeen_, Wolf__Crystal, Grass_Carp, PMC_Team"
logoFile="logo.png" 
displayURL="https://space.bilibili.com/362855464" 
credits="PMC_Team"
description="A mod that brings Plants vs Zombies to Minecraft !"
configBackground="pvz:textures/block/amethyst_block.png"

[[dependencies.pvz]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.39,)"
    
[[dependencies.pvz]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"